[features]
seeds = false
[programs.localnet]
solana_nft_collaterized_loans = "7Ags9aVzdyCP2SALzWhgRJG8VRAsPiAs5wGCTEn2PMTr"

[programs.devnet]
solana_nft_collaterized_loans = "7Ags9aVzdyCP2SALzWhgRJG8VRAsPiAs5wGCTEn2PMTr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/alex/blockchain/Keys/alex.json"
#wallet = "/home/alex/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
